apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: YIT PLACEMENT
type: Opaque
data:
  mongo-root-username: YWRtaW4=     # base64("admin")
  mongo-root-password: YWRtaW4=     # base64("admin")

